name: CI
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set-up Bun
        uses: oven-sh/setup-bun@v1
      - name: Set-up Encoped
        run: cargo install --git https://github.com/Brian3647/encoped
      - name: build
        run: bun run build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}
